version: "3.7"

services:
    node:
        build:
            context: .
            dockerfile: docker/dev/node/Dockerfile
        volumes:
            - .:/app
        ports:
            - "8080:80"