export const ACTIVE_ORDERS_CALLCENTER = "ACTIVE_ORDERS_CALLCENTER";
export const ACTIVE_ORDERS_KITCHEN = "ACTIVE_ORDERS_KITCHEN";
export const ACTIVE_ORDERS_COOK = "ACTIVE_ORDERS_COOK";
export const REJECTED_ORDERS_CALLCENTER = "REJECTED_ORDERS_CALLCENTER";
export const ACTIVE_ORDERS_COURIER = "ACTIVE_ORDERS_COURIER";
