export const OPEN_EDITORCALLCENTER = 'OPEN_EDITORCALLCENTER';
export const CLOSE_EDITORCALLCENTER = 'CLOSE_EDITORCALLCENTER';

export const OPEN_MODAL_FILTER = 'OPEN_MODAL_FILTER';
export const CLOSE_MODAL_FILTER = 'CLOSE_MODAL_FILTER';
