export const UPDATE_SETTINGS_DATA = "UPDATE_SETTINGS_DATA";
export const UPDATE_SETTINGS_CITIES_LIST = "UPDATE_SETTINGS_CITIES_LIST";
export const UPDATE_SETTINGS_KITCHENS_LIST = "UPDATE_SETTINGS_KITCHENS_LIST";
export const UPDATE_SETTINGS_LOCATIONS_LIST = "UPDATE_SETTINGS_LOCATIONS_LIST";
export const UPDATE_SETTINGS_CLIENT_SOURCES = "UPDATE_SETTINGS_CLIENT_SOURCES";
export const UPDATE_SETTINGS_PAYMENT_TYPES = "UPDATE_SETTINGS_PAYMENT_TYPES";
export const UPDATE_SETTINGS_ORDER_STATUSES = "UPDATE_SETTINGS_ORDER_STATUSES";
export const UPDATE_SETTINGS_ORDER_TYPES = "UPDATE_SETTINGS_ORDER_TYPES";
export const UPDATE_SETTINGS_ITEMS_STATUSES = "UPDATE_SETTINGS_ITEMS_STATUSES";
export const UPDATE_SETTINGS_PRODUCT_CATEGORIES =
  "UPDATE_SETTINGS_PRODUCT_CATEGORIES";
export const UPDATE_SETTINGS_PRODUCT_TYPES = "UPDATE_SETTINGS_PRODUCT_TYPES";
export const UPDATE_SETTINGS_ROLES_LIST = "UPDATE_SETTINGS_ROLES_LIST";
