export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_FULL_USERS = 'UPDATE_FULL_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const UPDATE_EDITED_USER = 'UPDATE_EDITED_USER';
export const CLEAR_EDITED_USER = 'CLEAR_EDITED_USER';
